language: php

env:
  - XDEBUG_MODE=coverage

php:
  - 8.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit --configuration phpunit.xml tests

after_success:
  - bash <(curl -s https://codecov.io/bash)