name: Run tests
on: [ push ]
jobs:
    run-mutation-tests:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout sources
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    tools: composer:v2
                    coverage: xdebug

            -   name: Composer install
                run: composer install

            -   name: Run mutation tests
                run: vendor/bin/infection --show-mutations
